# -*- coding: utf-8 -*-
"""AI lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPtYKWPShFsUEjLeFyzUsY5TwVY88OW-
"""

import random
import heapq

# -------------------------------
# Sorting Algorithms
# -------------------------------

def bubble_sort(arr):
    a = arr.copy()
    n = len(a)
    for i in range(n):
        swapped = False
        for j in range(0, n - i - 1):
            if a[j] > a[j + 1]:
                a[j], a[j + 1] = a[j + 1], a[j]
                swapped = True
        if not swapped:
            break
    return a

def selection_sort(arr):
    a = arr.copy()
    n = len(a)
    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if a[j] < a[min_index]:
                min_index = j
        a[i], a[min_index] = a[min_index], a[i]
    return a

def insertion_sort(arr):
    a = arr.copy()
    for i in range(1, len(a)):
        key = a[i]
        j = i - 1
        while j >= 0 and a[j] > key:
            a[j + 1] = a[j]
            j -= 1
        a[j + 1] = key
    return a

def merge_sort(arr):
    if len(arr) <= 1:
        return arr.copy()

    mid = len(arr) // 2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])

    merged = []
    i = 0
    j = 0

    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            merged.append(left[i])
            i += 1
        else:
            merged.append(right[j])
            j += 1

    while i < len(left):
        merged.append(left[i])
        i += 1

    while j < len(right):
        merged.append(right[j])
        j += 1

    return merged

def quick_sort(arr):
    if len(arr) <= 1:
        return arr.copy()

    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quick_sort(left) + middle + quick_sort(right)

def heap_sort(arr):
    heap = arr.copy()
    heapq.heapify(heap)
    sorted_list = []

    while heap:
        sorted_list.append(heapq.heappop(heap))

    return sorted_list

# -------------------------------
# Helper Functions for Smart Sort
# -------------------------------

def is_nearly_sorted(arr):
    if len(arr) < 2:
        return True

    disorder_count = 0
    for i in range(len(arr) - 1):
        if arr[i] > arr[i + 1]:
            disorder_count += 1

    return disorder_count <= max(1, len(arr) // 10)

def has_many_duplicates(arr):
    if len(arr) == 0:
        return False

    unique_ratio = len(set(arr)) / len(arr)
    return unique_ratio < 0.6

def choose_sorting_algorithm(arr):
    n = len(arr)

    if n <= 10:
        return "Insertion Sort", insertion_sort

    elif is_nearly_sorted(arr):
        return "Insertion Sort", insertion_sort

    elif has_many_duplicates(arr):
        return "Merge Sort", merge_sort

    elif n > 100:
        return "Quick Sort", quick_sort

    else:
        return "Heap Sort", heap_sort

def smart_sort(arr):
    algorithm_name, algorithm_function = choose_sorting_algorithm(arr)
    sorted_arr = algorithm_function(arr)
    return algorithm_name, sorted_arr

# -------------------------------
# Main Program
# -------------------------------

def main():
    print("Hafeez AI LAB")
    print("-----------------------")

    numbers = list(map(int, input("Enter numbers separated by spaces:\n").split()))

    print("\nYour entered List:", numbers)

    algorithm_used, sorted_numbers = smart_sort(numbers)

    print("Chosen Algorithm:", algorithm_used)
    print("Sorted List:", sorted_numbers)

if __name__ == "__main__":
    main()